### ISSUE TITLE
Crawling Peers and Local Ark-Nodes

### ISSUE THREAD

**Issue by jcrubino** [Moustikitos/arky#21]
1. How can Arky be used to get peers of peers?
2. How can Arky use a local ark-node?

**Comment by Moustikitos** [comment]
1. Arky automaticaly does it, peers in the `*.net` file are seeds. They are used to find peers and arky loop on them regurarly during cli sessions.
2. I think you can put "http://localhost:<port>" in peers field of `*.net` file, never tried, but should work.
